import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Manually ordered (not autogenerated) so the guide reads top-to-bottom the
 * way a new Nordiq contributor should encounter it: what the platform is,
 * how it's built, where each repo fits, then how AI subagents are used to
 * develop it.
 */
const sidebars: SidebarsConfig = {
  guideSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      link: {type: 'doc', id: 'architecture/overview'},
      items: [
        'architecture/overview',
        'architecture/platform-conventions',
        'architecture/data-model',
        'architecture/event-bus',
      ],
    },
    {
      type: 'category',
      label: 'Repos',
      link: {type: 'doc', id: 'repos/overview'},
      items: [
        'repos/overview',
        'repos/nds',
        'repos/nas',
        'repos/shovl',
        'repos/mission-control',
        'repos/website',
      ],
    },
    {
      type: 'category',
      label: 'AI Agent Context',
      link: {type: 'doc', id: 'ai-agent-context/overview'},
      items: [
        'ai-agent-context/overview',
        'ai-agent-context/subagents',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: ['examples/generate-quote'],
    },
  ],
};

export default sidebars;
